export enum ValidationType {
  COMMAND = "COMMAND",

  DIRECTORY_EXISTS = "DIRECTORY_EXISTS",

  FILE_EXISTS = "FILE_EXISTS",

  FILE_CONTAINS = "FILE_CONTAINS",

  COMMAND_OUTPUT = "COMMAND_OUTPUT",

  REGEX = "REGEX",

  PERMISSION = "PERMISSION",

  USER_EXISTS = "USER_EXISTS",

  PROCESS_RUNNING = "PROCESS_RUNNING",

  CUSTOM_SCRIPT = "CUSTOM_SCRIPT",
}